configurations:
  icons:
    - "wooden_sword"
    - "stone_sword"
    - "iron_sword"
    - "golden_sword"
    - "diamond_sword"
    #
    - "iron_pickaxe"
    - "diamond_pickaxe"
    - "iron_chestplate"
    - "golden_chestplate"
    - "diamond_chestplate"
    #
    - "iron_axe"
    - "golden_axe"
    - "stick"
    - "anvil"
    - "enchanting_table"
    #
    - "chest"
    - "bookshelf"
    - "tnt"
    - "bedrock"
    - "packed_ice"
    #
    - "grass_block"
    - "cobblestone"
    - "bread"
    - "water_bottle"
    - "ender_pearl"
items:
  blaze_powder: "blaze powder"
  redstone: "redstone"
  glowstone: "glowstone"
  water_bottle: "water bottle"
  nether_wart: "nether wart item"
  fermented_spider_eye: "fermented spider eye"
  gun_powder: "gun powder"
  #
  golden_carrot: "golden carrot"
  rabbit_foot: "rabbit foot"
  magma_cream: "magma cream"
  sugar: "sugar"
  pufferfish: "pufferfish"
  golden_melon: "golden melon"
  spider_eye: "spider eye"
  ghast_tear: "ghast tear"
  #
  night_vision_potion: "night vision potion"
  invisibility_potion: "invisibility potion"
  leaping_potion: "leaping potion"
  fire_resistance_potion: "fire resistance potion"
  speed_potion: "speed potion"
  slowness_potion: "slowness potion"
  water_breathing_potion: "water breathing potion"
  health_potion: "health potion"
  harming_potion: "harming potion"
  poison_potion: "poison potion"
  regeneration_potion: "regeneration potion"
  strength_potion: "strength potion"
  weakness_potion: "weakness potion"
  #
  extended_night_vision_potion: "extended night vision potion"
  extended_invisibility_potion: "extended invisibility potion"
  extended_leaping_potion: "extended leaping potion"
  extended_fire_resistance_potion: "extended fire resistance potion"
  extended_speed_potion: "extended speed potion"
  extended_slowness_potion: "extended slowness potion"
  extended_water_breathing_potion: "extended water breathing potion"
  extended_poison_potion: "extended poison potion"
  extended_regeneration_potion: "extended regeneration potion"
  extended_strength_potion: "extended strength potion"
  extended_weakness_potion: "extended weakness potion"
  #
  strong_leaping_potion: "strong leaping potion"
  strong_speed_potion: "strong speed potion"
  strong_health_potion: "strong health potion"
  strong_harming_potion: "strong harming potion"
  strong_poison_potion: "strong poison potion"
  strong_regeneration_potion: "strong regeneration potion"
  strong_strength_potion: "strong strength potion"
  #
  splash_night_vision_potion: "splash potion of night vision"
  splash_invisibility_potion: "splash potion of invisibility"
  splash_leaping_potion: "splash potion of leaping"
  splash_fire_resistance_potion: "splash potion of fire resistance"
  splash_speed_potion: "splash potion of speed"
  splash_slowness_potion: "splash potion of slowness"
  splash_water_breathing_potion: "splash potion of water breathing"
  splash_health_potion: "splash potion of health"
  splash_harming_potion: "splash potion of harming"
  splash_poison_potion: "splash potion of poison"
  splash_regeneration_potion: "splash potion of regeneration"
  splash_strength_potion: "splash potion of strength"
  splash_weakness_potion: "splash potion of weakness"
  #
  splash_extended_night_vision_potion: "splash potion of extended night vision"
  splash_extended_invisibility_potion: "splash potion of extended invisibility"
  splash_extended_leaping_potion: "splash potion of extended leaping"
  splash_extended_fire_resistance_potion: "splash potion of extended fire resistance"
  splash_extended_speed_potion: "splash potion of extended speed"
  splash_extended_slowness_potion: "splash potion of extended slowness"
  splash_extended_water_breathing_potion: "splash potion of extended water breathing"
  splash_extended_poison_potion: "splash potion of extended poison"
  splash_extended_regeneration_potion: "splash potion of extended regeneration"
  splash_extended_strength_potion: "splash potion of extended strength"
  splash_extended_weakness_potion: "splash potion of extended weakness"
  #
  splash_strong_leaping_potion: "splash potion of strong leaping"
  splash_strong_speed_potion: "splash potion of strong speed"
  splash_strong_health_potion: "splash potion of strong health"
  splash_strong_harming_potion: "splash potion of strong harming"
  splash_strong_poison_potion: "splash potion of strong poison"
  splash_strong_regeneration_potion: "splash potion of strong regeneration"
  splash_strong_strength_potion: "splash potion of strong strength"
  #
  wooden_sword: "wooden sword"
  stone_sword: "stone sword"
  iron_sword: "iron sword"
  golden_sword: "golden sword"
  diamond_sword: "diamond sword"
  #
  iron_pickaxe: "iron pickaxe"
  diamond_pickaxe: "diamond pickaxe"
  iron_chestplate: "iron chestplate"
  golden_chestplate: "golden chestplate"
  diamond_chestplate: "diamond chestplate"
  #
  iron_axe: "iron axe"
  golden_axe: "golden axe"
  stick: "stick"
  anvil: "anvil"
  enchanting_table: "enchanting table"
  #
  chest: "chest"
  bookshelf: "bookshelf"
  tnt: "tnt"
  bedrock: "bedrock"
  packed_ice: "packed ice"
  #
  grass_block: "grass block"
  cobblestone: "cobblestone"
  bread: "bread"
  ender_pearl: "ender pearl"